version: '3.9'
services:
  frontend:
    image: nginx:stable-alpine
    container_name: music-dating-frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
