version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dev-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: music_dating_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./server
    container_name: music-dating-backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: