version: '3.8'

services:
  db:
    image: postgres:16
    container_name: music_dating_db
    restart: always
    environment:
      POSTGRES_DB: music_dating_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: local_dockerfile
    env_file:
      - local-docker.env
    ports:
      - "8088:8088"
    depends_on:
      - db

volumes:
  pg_data: