version: '3.8'

services:
  db:
    image: postgres:16
    container_name: music_dating_db
    restart: always
    environment:
      POSTGRES_DB: music_dating_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
