version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dev-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: music_dating_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: music-dating-backend
    image: openjdk:21-jdk-slim
    working_dir: /app
    volumes:
      - ./:/app            # код Spring Boot из папки server
    env_file:
      - .env               # переменные окружения
    ports:
      - "8080:8080"      # порт приложения
    depends_on:
      - postgres
    command: sh -c "chmod +x ./gradlew && ./gradlew bootRun"
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    driver: bridge