version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dev-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: music_dating_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
