name: Main CD

on:
  push:
    branches: [main]

env:
  SERVER_IP: "85.208.86.160"
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Backend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.SERVER_IP }}
          username: ubuntu
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/music-dating
            git pull origin main
            ./gradlew -p backend clean build
            sudo systemctl restart backend

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.SERVER_IP }}
          script: |
            cd /opt/music-dating/frontend
            npm ci
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl reload nginx